### ISSUE TITLE
distinguish odd and even weeks

### ISSUE THREAD

**Issue by xieleo5** [BoYanZh/QQGroupRepeater#14]
求dalao搞个分辨单双周的功能，没开学多久已经有个朋友搞不清了qaq

**Comment by Scarlet-Climax** [comment]
![image](https://user-images.githubusercontent.com/6814555/65563921-c6291d00-df7d-11e9-8c09-11e166ba7559.png)

See the week number below plz.

**Comment by BoYanZh** [comment]
OK.
